"""
PDF report generator using ReportLab.

Produces a clean, professional, multi-section PDF with:
- Cover header (title, period, generated by, timestamp)
- Executive summary
- Sections (with embedded tables where data is structured)
- Footer with page numbers
"""
from io import BytesIO
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, mm
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, KeepTogether, HRFlowable,
)


# ─── Brand colors ─────────────────────────────────────────
BRAND_DARK = colors.HexColor("#0a0f1a")
BRAND_BLUE = colors.HexColor("#2d5cd6")
BRAND_LIGHT = colors.HexColor("#7dd3fc")
TEXT_PRIMARY = colors.HexColor("#1e293b")
TEXT_MUTED = colors.HexColor("#64748b")
ROW_ALT = colors.HexColor("#f1f5f9")


def _styles():
    base = getSampleStyleSheet()
    styles = {
        "title": ParagraphStyle(
            "title", parent=base["Heading1"],
            fontName="Helvetica-Bold", fontSize=20, textColor=BRAND_DARK,
            spaceAfter=4, alignment=TA_LEFT,
        ),
        "subtitle": ParagraphStyle(
            "subtitle", parent=base["Normal"],
            fontName="Helvetica", fontSize=10, textColor=TEXT_MUTED,
            spaceAfter=14,
        ),
        "h2": ParagraphStyle(
            "h2", parent=base["Heading2"],
            fontName="Helvetica-Bold", fontSize=13, textColor=BRAND_BLUE,
            spaceBefore=14, spaceAfter=6,
        ),
        "summary": ParagraphStyle(
            "summary", parent=base["Normal"],
            fontName="Helvetica", fontSize=10.5, textColor=TEXT_PRIMARY,
            leading=15, alignment=TA_JUSTIFY, spaceAfter=10,
        ),
        "body": ParagraphStyle(
            "body", parent=base["Normal"],
            fontName="Helvetica", fontSize=10, textColor=TEXT_PRIMARY,
            leading=14, alignment=TA_JUSTIFY, spaceAfter=6,
        ),
        "small": ParagraphStyle(
            "small", parent=base["Normal"],
            fontName="Helvetica", fontSize=8.5, textColor=TEXT_MUTED, leading=11,
        ),
        "label": ParagraphStyle(
            "label", parent=base["Normal"],
            fontName="Helvetica-Bold", fontSize=8.5, textColor=TEXT_MUTED,
            leading=11,
        ),
    }
    return styles


def _on_page(canvas, doc):
    """Footer with page number."""
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(TEXT_MUTED)
    page_num = f"Page {canvas.getPageNumber()}"
    canvas.drawRightString(A4[0] - 20 * mm, 12 * mm, page_num)
    canvas.drawString(20 * mm, 12 * mm, "AAR — عينك عالرجعة · Confidential")
    canvas.restoreState()


def _kv_table(rows, styles):
    """Two-column key-value table."""
    data = [[Paragraph(k, styles["label"]), Paragraph(str(v), styles["body"])] for k, v in rows]
    t = Table(data, colWidths=[1.5 * inch, 4.0 * inch])
    t.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    return t


def _data_table(headers, rows, col_widths=None, styles=None):
    """Header + data table with alternating row colors."""
    table_data = [headers] + rows
    t = Table(table_data, colWidths=col_widths, repeatRows=1)
    style_cmds = [
        ("BACKGROUND", (0, 0), (-1, 0), BRAND_BLUE),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("ALIGN", (0, 0), (-1, 0), "LEFT"),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 6),
        ("TOPPADDING", (0, 0), (-1, 0), 6),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, -1), 8.5),
        ("TEXTCOLOR", (0, 1), (-1, -1), TEXT_PRIMARY),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 1), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 4),
    ]
    for i in range(2, len(table_data), 2):
        style_cmds.append(("BACKGROUND", (0, i), (-1, i), ROW_ALT))
    t.setStyle(TableStyle(style_cmds))
    return t


def _render_section_data(data: dict, styles):
    """Convert structured section data into ReportLab flowables."""
    flow = []
    if not data:
        return flow

    t = data.get("type")

    if t == "alerts_breakdown":
        sev_rows = [[k.upper(), str(v)] for k, v in data.get("by_severity", {}).items()]
        if sev_rows:
            flow.append(Paragraph("By Severity", styles["label"]))
            flow.append(_data_table(["Severity", "Count"], sev_rows, [3 * inch, 1.5 * inch]))
            flow.append(Spacer(1, 8))
        zone_rows = [[k.replace("_", " ").title(), str(v)] for k, v in data.get("by_zone", {}).items()]
        if zone_rows:
            flow.append(Paragraph("By Zone (Top 5)", styles["label"]))
            flow.append(_data_table(["Zone", "Alert Count"], zone_rows, [3 * inch, 1.5 * inch]))

    elif t == "queue_zones":
        rows = [[z.replace("_", " ").title(), str(v.get("avg", 0)), str(v.get("peak", 0))]
                for z, v in data.get("zones", {}).items()]
        if rows:
            flow.append(_data_table(
                ["Zone", "Avg Occupancy", "Peak"], rows,
                [2.5 * inch, 1.5 * inch, 1.0 * inch]
            ))

    elif t == "suspicious_breakdown":
        type_rows = [[k, str(v)] for k, v in data.get("by_type", {}).items()]
        if type_rows:
            flow.append(Paragraph("By Activity Type", styles["label"]))
            flow.append(_data_table(["Activity", "Count"], type_rows, [3.5 * inch, 1.0 * inch]))
            flow.append(Spacer(1, 8))

        items = data.get("items", [])
        if items:
            flow.append(Paragraph("Detailed Reports", styles["label"]))
            rows = []
            for it in items:
                ts = it.get("created_at") or ""
                if ts:
                    ts = ts.replace("T", " ")[:16]
                rows.append([
                    ts,
                    it.get("zone", "-").replace("_", " "),
                    it.get("activity_type", "-")[:30],
                    (it.get("reported_by") or "-")[:14],
                    (it.get("notes") or "-")[:40],
                ])
            flow.append(_data_table(
                ["Time", "Zone", "Activity", "Reporter", "Notes"], rows,
                [1.1 * inch, 1.0 * inch, 1.5 * inch, 0.9 * inch, 1.5 * inch],
            ))

    elif t == "alert_list":
        items = data.get("items", [])
        rows = []
        for it in items:
            ts = it.get("created_at") or ""
            if ts:
                ts = ts.replace("T", " ")[:16]
            rows.append([
                ts,
                (it.get("severity") or "-").upper(),
                it.get("zone", "-").replace("_", " ")[:18],
                (it.get("alert_type") or "-").replace("_", " ")[:18],
                "✓" if it.get("acknowledged") else "—",
                (it.get("message") or "-")[:38],
            ])
        if rows:
            flow.append(_data_table(
                ["Time", "Severity", "Zone", "Type", "Ack", "Message"], rows,
                [1.1 * inch, 0.7 * inch, 1.0 * inch, 1.0 * inch, 0.4 * inch, 1.8 * inch],
            ))

    return flow


def render_report_pdf(report: dict) -> bytes:
    """Render the report dict to PDF bytes."""
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=20 * mm, rightMargin=20 * mm,
        topMargin=18 * mm, bottomMargin=20 * mm,
        title=report.get("title", "Operations Report"),
        author="AAR System",
    )
    styles = _styles()
    flow = []

    # Header
    flow.append(Paragraph(report.get("title", "Operations Report"), styles["title"]))
    flow.append(Paragraph("AAR — عينك عالرجعة · Beirut–Rafic Hariri International Airport", styles["subtitle"]))
    flow.append(HRFlowable(width="100%", thickness=0.6, color=BRAND_BLUE, spaceBefore=0, spaceAfter=10))

    # Metadata
    pf = report.get("period_from")
    pt = report.get("period_to")
    if isinstance(pf, datetime): pf = pf.strftime("%Y-%m-%d %H:%M UTC")
    if isinstance(pt, datetime): pt = pt.strftime("%Y-%m-%d %H:%M UTC")
    flow.append(_kv_table([
        ("Report Type", report.get("report_type", "-").upper()),
        ("Period From", pf or "-"),
        ("Period To", pt or "-"),
        ("Generated By", report.get("generated_by", "-")),
        ("Generated At", datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")),
    ], styles))
    flow.append(Spacer(1, 14))

    # Executive Summary
    flow.append(Paragraph("Executive Summary", styles["h2"]))
    flow.append(Paragraph(report.get("summary", "No summary available."), styles["summary"]))

    # Sections
    for sec in report.get("sections", []):
        flow.append(Paragraph(sec.get("heading", "Section"), styles["h2"]))
        if sec.get("content"):
            flow.append(Paragraph(sec["content"], styles["body"]))
            flow.append(Spacer(1, 4))
        sub_flow = _render_section_data(sec.get("data") or {}, styles)
        for f in sub_flow:
            flow.append(f)

    flow.append(Spacer(1, 18))
    flow.append(HRFlowable(width="100%", thickness=0.4, color=TEXT_MUTED))
    flow.append(Spacer(1, 4))
    flow.append(Paragraph(
        "This report was automatically generated by the AAR AI Assistant based on collected operational data. "
        "All times are in UTC unless otherwise noted.",
        styles["small"],
    ))

    doc.build(flow, onFirstPage=_on_page, onLaterPages=_on_page)
    return buf.getvalue()
